#!/usr/bin/env npx tsx
/**
 * Regenerates intent cheatsheet from schema-contract source of truth.
 * Run: npm run codegen:intent
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = resolve(ROOT, "packages/agent/src/intent/schema-contract.ts");
const OUT_DIR = resolve(ROOT, "packages/agent/src/intent/generated");
const OUT = resolve(OUT_DIR, "intent-cheatsheet.ts");

const raw = readFileSync(SRC, "utf8");
const match = raw.match(/export const INTENT_SCHEMA_CHEATSHEET_SOURCE = `([\s\S]*?)`;/);
if (!match) {
  console.error("[codegen:intent] INTENT_SCHEMA_CHEATSHEET_SOURCE not found");
  process.exit(1);
}

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(
  OUT,
  `/** Generated by scripts/codegen-intent-cheatsheet.ts — do not edit. */\nexport const INTENT_SCHEMA_CHEATSHEET = \`${match[1]}\`;\n`,
  "utf8",
);
console.log(`[codegen:intent] wrote ${OUT}`);
